export const BUILDINGS = [
  {
    id: "bank",
    name: "First Realm Bank",
    icon: "🏦",
    description: "Your finances, your banker, your future",
    color: "emerald",
    available: true,
    href: "/buildings/bank",
    aiPersona: { name: "Morgan Wells", title: "Your Personal Banker", avatar: "MW" },
  },
  {
    id: "library",
    name: "City Library",
    icon: "📚",
    description: "Knowledge, files, study rooms & AI professors",
    color: "blue",
    available: true,
    href: "/buildings/library",
    aiPersona: { name: "Prof. Elena Vasquez", title: "Head Librarian & Professor", avatar: "EV" },
  },
  {
    id: "university",
    name: "Realm University",
    icon: "🎓",
    description: "Courses, campus life, clubs & study groups",
    color: "violet",
    available: false,
    href: "/buildings/university",
    aiPersona: { name: "Dean Carter", title: "Academic Advisor", avatar: "DC" },
  },
  {
    id: "gym",
    name: "Iron District Gym",
    icon: "🏋️",
    description: "Fitness plans, AI trainer & health tracking",
    color: "orange",
    available: false,
    href: "/buildings/gym",
    aiPersona: { name: "Coach Tyler Brooks", title: "Personal Trainer", avatar: "TB" },
  },
  {
    id: "home",
    name: "Your Home",
    icon: "🏠",
    description: "Dashboard, reminders, personal AI & chores",
    color: "amber",
    available: false,
    href: "/buildings/home",
    aiPersona: { name: "ARIA", title: "Personal Assistant", avatar: "AI" },
  },
  {
    id: "hospital",
    name: "Realm Medical",
    icon: "🏥",
    description: "Health records, prescriptions & wellness",
    color: "red",
    available: false,
    href: "/buildings/hospital",
    aiPersona: { name: "Dr. Patel", title: "Chief of Medicine", avatar: "DP" },
  },
  {
    id: "mall",
    name: "The Mall",
    icon: "🛍️",
    description: "Shop Amazon, Walmart, Costco & more",
    color: "pink",
    available: false,
    href: "/buildings/mall",
    aiPersona: { name: "Sam", title: "Shopping Assistant", avatar: "SA" },
  },
  {
    id: "government",
    name: "City Hall",
    icon: "🏛️",
    description: "Civic info, forms, IDs & public services",
    color: "slate",
    available: false,
    href: "/buildings/government",
    aiPersona: { name: "Officer Rivera", title: "City Services Advisor", avatar: "OR" },
  },
  {
    id: "office",
    name: "The Office Tower",
    icon: "💼",
    description: "Work projects, tasks & team collaboration",
    color: "cyan",
    available: false,
    href: "/buildings/office",
    aiPersona: { name: "Alex Chen", title: "Productivity Coach", avatar: "AC" },
  },
] as const

export type BuildingId = typeof BUILDINGS[number]["id"]

export function getBuilding(id: string) {
  return BUILDINGS.find((b) => b.id === id)
}
